### ISSUE TITLE
Please remove the Android ID from Mediteo app (app token : t7fqydekq238)

### ISSUE THREAD

**Issue by UlviyyaB** [katiehutch/NinjaWarriors#2]
**Account name: Mediteo gmbh**
**Account #: 6833**
**App Token: t7fqydekq238**

@slamspitfolksong

The client has entered two app IDs at the beginning, as they initially wanted to have a multiplatform app. But now they created a new Android app in the dashboard and would like to have both apps separately. This app - app token : t7fqydekq238 - has both iOS & Android app IDs entered though.

Please remove the Android app ID and leave iOS app ID only.

**Comment by slamspitfolksong** [comment]
opened in dashboard please close here @UlviyyaB
